insert into users values (1, 18, 'Dnipro', 'Oleg', 'Surmane');
insert into users values (2, 44, 'Kyiv', 'Vlad', 'Schoop');
insert into users values (3, 29, 'Lviv', 'Andrii', 'Honey');
insert into users values (4, 22, 'Aachen', 'Ivan', 'Chop');
insert into users values (5, 52, 'Dnipro', 'Daniil', 'Mercedes');
insert into users values (6, 19, 'Enshede', 'Olga', 'Busy');
insert into users values (7, 27, 'Los Angeles', 'Valerii', 'Physics');
insert into users values (8, 25, 'Kyiv', 'Pavel', 'Anwalt');
insert into users values (9, 32, 'Lviv', 'Glib', 'Itenjoyer');
insert into users values (10, 19, 'Aachen', 'Fedor', 'Schwerboss');
insert into users values (11, 29, 'Dnipro', 'Anna', 'Wissen');
insert into users values (12, 23, 'Aachen', 'Sofia', 'White');
insert into users values (13, 31, 'Lviv', 'Elisabeth', 'Foltor');
insert into users values (14, 21, 'Enshede', 'Meggie', 'Great');
insert into users values (15, 25, 'Los Angeles', 'Connor', 'Math');
insert into users values (16, 20, 'New York', 'Arnold', 'Figure');
insert into users values (17, 21, 'Kyiv', 'Matt', 'Cool');
insert into users values (18, 26, 'Kyiv', 'Eddie', 'Lindemenn');
insert into users values (19, 37, 'Lviv', 'Luce', 'Bergmann');
insert into users values (20, 30, 'Dnipro', 'Ben', 'Menn');
insert into users values (21, 29, 'Dnipro', 'Rosa', 'Klinge');

insert into books(id, author, title, category, description, price) values (1, 'Richard Powers', 'The Gold Bug Variations', 'Fiction', '', 41.99);
insert into books(id, author, title, category, description, price) values (2, 'Chimamanda Ngozi Adichie', 'Americanah', 'Fiction', '', 41.99);
insert into books(id, author, title, category, description, price) values (3, 'Octavia Butler', 'Parable of the Sower', 'Science Fiction', '', 41.99);
insert into books(id, author, title, category, description, price) values (4, 'Haruki Murakami', 'Kafka on the Shore', 'Fiction', '', 41.99);
insert into books(id, author, title, category, description, price) values (5, 'Jhumpa Lahiri', 'The Namesake', 'Fiction', '', 31.99);
insert into books(id, author, title, category, description, price) values (6, 'Margaret Atwood', 'The Handmaid''s Tale', 'Fiction', '', 31.99);
insert into books(id, author, title, category, description, price) values (7, 'Gabriel Garcia Marquez', 'One Hundred Years of Solitude', 'Fiction', '', 31.99);
insert into books(id, author, title, category, description, price) values (8, 'Cormac McCarthy', 'Blood Meridian', 'Western', '', 31.99);
insert into books(id, author, title, category, description, price) values (9, 'Donna Tartt', 'The Secret History', 'Fiction', '', 21.99);
insert into books(id, author, title, category, description, price) values (10, 'Salman Rushdie', 'Midnight''s Children	', 'Fiction', '', 21.99);
insert into books(id, author, title, category, description, price) values (11, 'Zadie Smith', 'White Teeth', 'Fiction', '', 21.99);
insert into books(id, author, title, category, description, price) values (12, 'Michael Crichton', 'Jurassic Park', 'Science Fiction', '', 21.99);
insert into books(id, author, title, category, description, price) values (13, 'George R.R. Martin', 'A Game of Thrones', 'Fantasy', '', 51.99);
insert into books(id, author, title, category, description, price) values (14, 'Terry Pratchett', 'Good Omens', 'Fantasy', '', 51.99);
insert into books(id, author, title, category, description, price) values (15, 'Neil Gaiman', 'American Gods', 'Fantasy', '', 51.99);
insert into books(id, author, title, category, description, price) values (16, 'J.R.R. Tolkien', 'The Hobbit', 'Fantasy', '', 51.99);
insert into books(id, author, title, category, description, price) values (17, 'Ursula K. Le Guin', 'The Left Hand of Darkness', 'Science Fiction', '', 11.99);
insert into books(id, author, title, category, description, price) values (18, 'Ernest Hemingway', 'The Old Man and the Sea', 'Fiction', '', 11.99);
insert into books(id, author, title, category, description, price) values (19, 'Kurt Vonnegut', 'Slaughterhouse-Five', 'Fiction', '', 11.99);
insert into books(id, author, title, category, description, price) values (20, 'Ray Bradbury', 'Fahrenheit 451', 'Science Fiction', '', 11.99);